"""Domain layer: pure types and ports."""

from .chunking import (
    Chunker,
    ChunkerConfig,
    ChunkingResult,
    ChunkOutput,
    compute_chunk_hash,
    compute_chunker_config_hash,
)
from .models import (
    Chunk,
    Document,
    DocumentStatus,
    DocumentVersion,
    IngestionTask,
    RetrievalProfile,
    Source,
    SourceType,
    Space,
    TaskOperation,
    TaskStage,
    TaskStatus,
)
from .parsing import (
    ParsedDocument,
    ParseError,
    ParseErrorCode,
    ParseMetadata,
    Parser,
    ParseResult,
    ParseSuccess,
    StructNode,
    StructNodeType,
    compute_blob_hash,
)
from .repositories import (
    ChunkRepository,
    DocumentRepository,
    DocumentVersionRepository,
    IngestionTaskRepository,
    SourceRepository,
    SpaceRepository,
)

__all__ = [
    "Chunk",
    "ChunkRepository",
    "Chunker",
    "ChunkerConfig",
    "ChunkingResult",
    "ChunkOutput",
    "Document",
    "DocumentRepository",
    "DocumentStatus",
    "DocumentVersion",
    "DocumentVersionRepository",
    "IngestionTask",
    "IngestionTaskRepository",
    "ParseError",
    "ParseErrorCode",
    "ParseMetadata",
    "ParseResult",
    "ParseSuccess",
    "ParsedDocument",
    "Parser",
    "RetrievalProfile",
    "Source",
    "SourceRepository",
    "SourceType",
    "Space",
    "SpaceRepository",
    "StructNode",
    "StructNodeType",
    "TaskOperation",
    "TaskStage",
    "TaskStatus",
    "compute_blob_hash",
    "compute_chunk_hash",
    "compute_chunker_config_hash",
]
