"""Repository ports (Protocols) for the core domain entities."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .models import (
    Chunk,
    Document,
    DocumentVersion,
    IngestionTask,
    Source,
    Space,
)


class SpaceRepository(Protocol):
    async def create(self, space: Space) -> Space: ...
    async def get(self, space_id: UUID) -> Space | None: ...
    # Declared before `list` so the `list[...]` annotation still resolves to the
    # builtin instead of the protocol's own `list` member.
    async def list_by_owner(self, owner_id: str) -> list[Space]: ...
    async def list(self) -> list[Space]: ...
    async def update(self, space: Space) -> Space: ...
    async def delete(self, space_id: UUID) -> None: ...


class SourceRepository(Protocol):
    async def create(self, source: Source) -> Source: ...
    async def get(self, source_id: UUID) -> Source | None: ...
    async def get_by_space(self, space_id: UUID) -> list[Source]: ...
    async def update(self, source: Source) -> Source: ...
    async def delete(self, source_id: UUID) -> None: ...


class DocumentRepository(Protocol):
    async def create(self, document: Document) -> Document: ...
    async def get(self, document_id: UUID) -> Document | None: ...
    async def get_by_source(self, source_id: UUID) -> list[Document]: ...
    async def get_by_stable_key(self, source_id: UUID, stable_key: str) -> Document | None: ...
    async def update(self, document: Document) -> Document: ...


class DocumentVersionRepository(Protocol):
    async def create(self, version: DocumentVersion) -> DocumentVersion: ...
    async def get(self, version_id: UUID) -> DocumentVersion | None: ...
    async def get_by_document(self, document_id: UUID) -> list[DocumentVersion]: ...
    async def get_latest(self, document_id: UUID) -> DocumentVersion | None: ...
    async def update(self, version: DocumentVersion) -> DocumentVersion: ...


class ChunkRepository(Protocol):
    async def create_batch(self, chunks: list[Chunk]) -> list[Chunk]: ...
    async def get_by_version(self, version_id: UUID) -> list[Chunk]: ...
    async def delete_by_version(self, version_id: UUID) -> int: ...


class IngestionTaskRepository(Protocol):
    async def create(self, task: IngestionTask) -> IngestionTask: ...
    async def get(self, task_id: UUID) -> IngestionTask | None: ...
    async def get_by_source(self, source_id: UUID) -> list[IngestionTask]: ...
    async def update(self, task: IngestionTask) -> IngestionTask: ...
    async def checkpoint(self) -> None: ...
