[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "application",
    "alembic",
    "infrastructure",
    "model-gateway",
    "fastapi",
    "python-multipart>=0.0.32",
    "uvicorn[standard]",
    "worker",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["api*"]
